version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
  redis: 
    image: redis
    volumes:
      - redis-data:/data
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3050:8080
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
  client:
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - /app/node_modules
      - ./client_ng:/app
    build:
      context: ./client_ng
      dockerfile: Dockerfile.dev
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  redis-data:
